queries = [
    "PyTorch: simple feed-forward neural network code snippet",
    "PyTorch: explain autograd functionality",
    "Keras: simple binary classification model code snippet",
    "Keras: explain callbacks usage",
    "HuggingFace Transformers: BERT fine-tuning code snippet",
    "HuggingFace Transformers: explain tokenization process",
    "spaCy: named entity recognition code snippet",
    "spaCy: explain pipeline architecture",
    "scikit-learn: create a pipeline with preprocessing and a model",
    "scikit-learn: explain cross-validation",
    "XGBoost: train model with hyperparameter tuning code",
    "LightGBM: explain gradient boosting",
    "CatBoost: train classifier with categorical features code",
    "CatBoost: explain handling of categorical variables",
    "Statsmodels: OLS regression code snippet",
    "Statsmodels: explain OLS regression assumptions",
    "pandas: dataset cleaning code snippet",
    "pandas: explain DataFrame indexing",
    "NumPy: matrix multiplication code snippet",
    "NumPy: explain benefits for numerical computations",
    "Seaborn: create a statistical plot example",
    "Plotly: create an interactive dashboard example",
    "DigitalOcean: create a Droplet via API code snippet",
    "Terraform: AWS EC2 instance configuration code",
    "Terraform: explain state management",
    "Docker: Dockerfile for a Python web application",
    "Docker: explain networking concepts",
    "Istio: VirtualService configuration example",
    "Helm: chart for a Kubernetes application code",
    "MongoDB: CRUD operations in Python code",
    "Cassandra: CQL query example",
    "Neo4j: Cypher query example",
    "Redis: Node.js operations code snippet",
    "RabbitMQ: implementation in Python code",
    "NATS: explain publish-subscribe model",
    "Milvus: implement vector similarity search code",
    "Vue.js: component fetching API data",
    "Svelte: build a two-way data binding component",
    "Next.js: page with server-side rendering",
    "Nuxt.js: dynamic routing page example",
    "Remix: loader function for data fetching",
    "Alpine.js: toggling element visibility snippet",
    "htmx: server-driven UI updates example",
    "Bootstrap: responsive navigation bar",
    "Tailwind CSS: style a button example",
    "Chakra UI: responsive card layout",
    "Material-UI: form with validation code",
    "Swift (iOS): view controller code example",
    "Flutter: counter app with state management",
    "React Native: cross-platform component example",
    "Ionic: page with navigation code",
    "Expo: access device sensors code snippet",
    "Capacitor: integrate native device features",
    "Jest: basic unit test example",
    "Mocha: test case for async function",
    "Selenium: form automation script",
    "Testing Library: React component test",
    "SonarQube: configure for JavaScript app",
    "Prometheus: monitoring configuration example",
    "Sentry: integrate error tracking in Python",
    "Flask: route handling GET/POST requests",
    "FastAPI: endpoint with Pydantic validation",
    "Spring Boot: create a RESTful API",
    "Ktor: server with JSON response",
    "Hapi: define routes example",
    "Xbox Live: authentication example",
    "Android: integrate Google Play Games services",
    "iOS: implement Game Center"
]
